name: ski_environment
channels:
  - defaults
dependencies:
  - pip
  - python=3.12
  - pip:
      - coverage==7.4.3
      - geocoder==1.38.1
      - numpy==1.26.4
      - pandas==2.2.1
      - pylint==3.1.0
      - pymongo==4.6.2
      - python-dotenv==1.0.1
      - streamlit==1.32.1
